echoのrouting imitial
hiroki-kondo-git/dayMemo_api_go pull request #4
Opened 2021-11-23 07:05 UTC by hiroki-kondo-git

必要となるechoでのroutingの初期構築
必要に応じてquery param, path paramなど指定しました

2021-11-24 15:10 UTC, ho2ri2s requested changes
命名だけおねしゃす！！
LGTM of the year

2021-11-24 15:10 UTC, ho2ri2s commented on memories/memory.go
> +func EditMemory(ctx echo.Context) error {
CRUDに沿うならここはUpdateのほうがよさそうね
```suggestion
func UpdateMemory(ctx echo.Context) error {
```

2021-11-24 15:10 UTC, ho2ri2s commented on users/user.go
> +func EditUser(ctx echo.Context) error {
ここもUpdateがよさそうね

2021-11-25 13:39 UTC, hiroki-kondo-git commented
修正したんでmergeしておきま

2021-11-25 14:08 UTC, merged